CoreTodosMVC/Models/ErrorViewModel.cs
using System;

namespace CoreTodosMVC.Models
{
  public class ErrorViewModel
  {
    public string RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
  }
}

CoreTodosMVC/Models/ToDoDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CoreTodosMVC.Models
{
  public class ToDoDbContext : DbContext
  {
    public ToDoDbContext(DbContextOptions<ToDoDbContext> options)
        : base (options) { } //ef core interception not generally available as of recording time

    public DbSet<ToDoItem> ToDoItems { get; set; }
  }
}

CoreTodosMVC/Models/ToDoItem.cs
namespace CoreTodosMVC.Models
{
  public class ToDoItem
  {
    public int Id { get; set; }
    public string Item { get; set; }
    public bool Completed { get; set; }
  }
}

CoreTodosMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CoreTodosMVC.Models;
using CoreFlogger;

namespace CoreTodosMVC.Controllers
{
  public class HomeController : Controller
  {
    [TrackUsage("ToDos", "Core MVC", "View Home")]
    public IActionResult Index()
    {
      return View();
    }

    [TrackUsage("ToDos", "Core MVC", "View Contact")]
    public IActionResult Contact()
    {
      ViewData["Message"] = "Your contact page.";

      return View();
    }

    public IActionResult Error()
    {
      return View(new ErrorViewModel {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

    //public IActionResult About()
    //{
    //  ViewData["Message"] = "Your application description page.";

    //  return View();
    //}

    //public IActionResult Privacy()
    //{
    //  return View();
    //}

    //[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    //public IActionResult Error()
    //{
    //  return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    //}
  }
}

CoreTodosMVC/Controllers/TodosController.cs
using CoreFlogger;
using CoreTodosMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace CoreTodosMVC.Controllers
{
  public class TodosController : Controller
  {
    private ToDoDbContext _db;

    public TodosController(ToDoDbContext context)
    {
      _db = context;
    }

    [TrackUsage("ToDos", "Core MVC", "View Todo List")]
    public async Task<IActionResult> Index()
    {
      return View(await _db.ToDoItems.ToListAsync());
    }

    public async Task<IActionResult> IndexError()
    {
      return View("Index", await _db.ToDoItems
        .Include("badstuff").ToListAsync());
    }

    public ActionResult Edit(int? id)
    {
      if (id == null)
        throw new ArgumentNullException("Todo Id should not be null!");

      WebHelper.LogWebDiagnostic("TodDos", "Core MVC",
        "Just checking in....", HttpContext,
        new Dictionary<string, object> { { "Very", "Important" } });

      var toDoItem = _db.ToDoItems.Find(id);
      if (toDoItem == null)
        throw new Exception($"No To-Do found with item numer [{id}]!");
      return View(toDoItem);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    [TrackUsage("ToDos", "Core MVC", "Edit ToDo")]
    public ActionResult Edit([Bind("Id", "Item", "Completed")] ToDoItem toDoItem)
    {
      if (ModelState.IsValid)
      {
        _db.Entry(toDoItem).State = EntityState.Modified;
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
      return View(toDoItem);
    }
  }
}

CoreTodosMVC/Controllers/TodosViaApiController.cs
using CoreTodosMVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CoreTodosMVC.Controllers
{
  [Authorize()]
  public class TodosViaApiController : Controller
  {
    public async Task<IActionResult> Index()
    {
      var todoList = await ApiHelper.GetListFromApiAsync<ToDoItem>(
        "/Todos", HttpContext);

      return View(todoList);
    }

    public async Task<IActionResult> IndexWithError()
    {
      var todoList = await ApiHelper.GetListFromApiAsync<ToDoItem>(
        "/Todos/Error", HttpContext);

      return View("Index", todoList);
    }

  }
}

CoreTodosMVC/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CoreTodosMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

CoreTodosMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoreTodosMVC</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CoreTodosMVC</a>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                <li><a asp-area="" asp-controller="Todos" asp-action="Index">Todos</a></li>
                <li><a asp-area="" asp-controller="Todos" asp-action="IndexError">Todos with Error</a></li>
                <li><a asp-area="" asp-controller="TodosViaApi" asp-action="Index">Secure Todos via API</a></li>
                <li><a asp-area="" asp-controller="TodosViaApi" asp-action="IndexWithError">Secure API with Error</a></li>
                <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
              </ul>
            </div>
        </div>
    </nav>

    @*<partial name="_CookieConsentPartial" />*@

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - CoreTodosMVC</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

CoreTodosMVC/Views/Todos/Edit.cshtml
@model ToDoItem

@{
  ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
  @Html.AntiForgeryToken()

  <div class="form-horizontal">
    <h4>To Do Item</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
      @Html.LabelFor(model => model.Item, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.EditorFor(model => model.Item, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Item, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => model.Completed, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        <div class="checkbox">
          @Html.EditorFor(model => model.Completed)
          @Html.ValidationMessageFor(model => model.Completed, "", new { @class = "text-danger" })
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Save" class="btn btn-default"
      </div>
    </div>
  </div>
}

<div>
  @Html.ActionLink("Back to List", "Indewx")
</div>

CoreTodosMVC/Views/Todos/Index.cshtml
@model IEnumerable<ToDoItem>

@{
    ViewData["Title"] = "Index";
}

<h2>To Do List</h2>

<p>
    <a asp-action="Create">Add New</a>
</p>
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Item)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Completed)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Item)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Completed)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
    }
    </tbody>
</table>

CoreTodosMVC/Views/TodosViaApi/Index.cshtml
@model IEnumerable<ToDoItem>

@{
  ViewData["Title"] = "Index";
}

<h2>To Do List From API</h2>

<p>
  <a asp-action="Create">Add New</a>
</p>
<table class="table table-striped">
  <thead>
    <tr>
      <th>
        @Html.DisplayNameFor(model => model.Item)
      </th>
      <th>
        @Html.DisplayNameFor(model => model.Completed)
      </th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    @foreach (var item in Model)
    {
      <tr>
        <td>
          @Html.DisplayFor(modelItem => item.Item)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.Completed)
        </td>
        <td>
          @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
          @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
      </tr>
    }
  </tbody>
</table>